language: python
sudo: false

python:
  - "3.4"
env:
  - PYTHONPATH=$PYTHONPATH:$PWD

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - python setup.py -q install

script:
  - make test

notifications:
    email: false
    slack: openbikes:2eVWLSI2CUwuds6LnquzalyG
