language: python
sudo: false

python:
  - "3.4"
env:
  - PYTHONPATH=$PYTHONPATH:$PWD

install:
  - python setup.py -q install
  - pip install -r requirements.txt

script:
  - make test

notifications:
    email: false
    slack: openbikes:2eVWLSI2CUwuds6LnquzalyG
